services:
  to_do:
    build: .
    image: to_do
    container_name: to_do
    ports:
      - 8000:8000
    command: >
      sh -c "./wait-for-it.sh db:5432 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    container_name: to_do_db
    environment:
      POSTGRES_USER: to_do
      POSTGRES_PASSWORD: password
      POSTGRES_DB: to_do

  adminer:
    image: adminer
    container_name: to_do_db_adminer
    restart: always
    ports:
      - 8080:8080
